# Generated by Django 5.0.4 on 2024-05-10 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filepath", models.FileField(upload_to="")),
                ("file_description", models.CharField(max_length=255, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("filename", models.CharField(max_length=255, null=True)),
                (
                    "file_type",
                    models.CharField(
                        default="other", max_length=50, verbose_name="File type"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
