# Generated by Django 5.0.4 on 2024-05-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="file_type",
            field=models.CharField(
                default="other", max_length=50, verbose_name="File type"
            ),
        ),
    ]
