# Generated by Django 5.0.4 on 2024-05-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_files", "0002_alter_userfile_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="filepath",
            field=models.FileField(upload_to=""),
        ),
    ]
