# Generated by Django 5.0.4 on 2024-04-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=320)),
                ("password", models.CharField(max_length=128)),
                ("avatar", models.TextField(blank=True, null=True)),
                ("role", models.CharField(default="user", max_length=10)),
            ],
        ),
    ]
